# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
- main
pr:
- main

variables:
  GOPATH: $(Agent.BuildDirectory)/go
  PATH: $(Agent.BuildDirectory)/go/bin:$(Agent.BuildDirectory)/go/src/github.com/hyperledger/fabric-ca/build/tools:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
  GOVER: 1.18.8

jobs:
- job: VerifyBuild
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: install_deps.yml
  - checkout: self
    path: 'go/src/github.com/hyperledger/fabric-ca'
    displayName: Checkout Fabric CA Code
  - script: make dist checks all-tests docs
    displayName: Run Unit and Integration Tests

- job: FVTTests
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: install_deps.yml
  - checkout: self
    path: 'go/src/github.com/hyperledger/fabric-ca'
    displayName: Checkout Fabric CA Code
  - script: make fvt-tests
    displayName: Run FVT Tests
