# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
- master
- release-2.*
- release-1.4
pr:
- master
- release-2.*
- release-1.4

variables:
  GOPATH: $(Agent.BuildDirectory)/go
  PATH: $(Agent.BuildDirectory)/go/bin:$(Agent.BuildDirectory)/go/src/github.com/hyperledger/fabric-ca/build/tools:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
  GOVER: 1.12.9

jobs:
- job: VerifyBuild
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: install_deps.yml
  - checkout: self
    path: 'go/src/github.com/hyperledger/fabric-ca'
    displayName: Checkout Fabric CA Code
  - script: make dist-all checks all-tests docs
    displayName: Run Unit and Integration Tests

- job: FVTTests
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: install_deps.yml
  - checkout: self
    path: 'go/src/github.com/hyperledger/fabric-ca'
    displayName: Checkout Fabric CA Code
  - script: make docker-fvt
    displayName: Build FVT Test Image
  - script: docker run -v $(pwd):/opt/gopath/src/github.com/hyperledger/fabric-ca hyperledger/fabric-ca-fvt
    displayName: Run FVT Tests

- job: DocBuild
  pool:
    vmImage: ubuntu-16.04
  container:
    image: n42org/tox:3.4.0
  steps:
  - checkout: self
    path: 'go/src/github.com/hyperledger/fabric-ca'
    displayName: Checkout Fabric CA Code
  - script: tox -edocs
    displayName: Build Documentation
  - publish: 'docs/_build/html'
    displayName: Publish Documentation
