# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
- release-1.4
pr:
- release-1.4

variables:
  GOPATH: $(Agent.BuildDirectory)/go
  PATH: $(Agent.BuildDirectory)/go/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
  GOVER: 1.14.12

jobs:
- job: VerifyBuild
  pool:
    vmImage: ubuntu-16.04
  dependsOn: []
  timeoutInMinutes: 60
  steps:
  - template: install_deps.yml
  - script: go get golang.org/x/tools/cmd/goimports
    displayName: Download goimports
  - checkout: self
    path: 'go/src/github.com/hyperledger/fabric-ca'
    displayName: Checkout Fabric CA Code
  - script: make dist-all unit-test int-tests docs
    displayName: Run Unit and Integration Tests

- job: FVTTests
  pool:
    vmImage: ubuntu-16.04
  dependsOn: []
  timeoutInMinutes: 60
  steps:
  - template: install_deps.yml
  - checkout: self
    path: 'go/src/github.com/hyperledger/fabric-ca'
    displayName: Checkout Fabric CA Code
  - script: make docker-fvt
    displayName: Build FVT Test Image
  - script: docker run -v $(pwd):/opt/gopath/src/github.com/hyperledger/fabric-ca hyperledger/fabric-ca-fvt
    displayName: Run FVT Tests

- job: DocBuild
  pool:
    vmImage: ubuntu-16.04
  dependsOn: []
  timeoutInMinutes: 60
  steps:
  - script: sudo apt-get clean && sudo apt-get update && sudo apt-get install -y python-minimal tox
    displayName: Install Tox
  - checkout: self
    path: 'go/src/github.com/hyperledger/fabric-ca'
    displayName: Checkout Fabric CA Code
  - script: tox -edocs
    displayName: Build Documentation
  - publish: 'docs/_build/html'
    displayName: Publish Documentation
