# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: Pull Request
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

env:
  GOPATH: /opt/go
  PATH: /opt/go/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
  GO_VER: 1.23.5

permissions:
  contents: read

jobs:
  verify-build:
    name: Verify Build
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt clean
        name: Run APT Clean
      - run: sudo apt update
        name: Run Apt Update
      - uses: actions/checkout@v4
        name: Checkout Fabric CA Code        
      - uses: actions/setup-go@v5
        name: Install Go
        with:
          go-version: ${{ env.GO_VER }}
      - run: make dist checks all-tests docs
        name: Run Unit and Integration Tests
  fvt-tests:
    name: FVT Tests
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt clean
        name: Run APT Clean
      - run: sudo apt update
        name: Run Apt Update
      - uses: actions/checkout@v4
        name: Checkout Fabric CA Code        
      - uses: actions/setup-go@v5
        name: Install Go
        with:
          go-version: ${{ env.GO_VER }}
      - run: make fvt-tests
        name: Run FVT Tests
