name: "Security vulnerability scan"

on:
  schedule:
    - cron: "22 22 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dev:
    name: Scan development codebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/scan

  release:
    name: Scan latest release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          sparse-checkout: |
            .github
      - name: Get latest releast tag
        id: latest-release
        run: echo "TAG=$(curl --location --silent --fail "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest" | jq --raw-output '.tag_name')" >> "${GITHUB_OUTPUT}"
      - name: Checkout release ${{ steps.latest-release.outputs.TAG }}
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ steps.latest-release.outputs.TAG }}
          path: src
      - uses: ./.github/actions/scan
        with:
          path: src
